language: go
sudo: false
go:
  - 1.8
  - 1.9
  - tip

matrix:
  include:
    - os: linux
      before_install:
        - go get NiuStar/utils
        - go get NiuStar/log
        - go get github.com/petermattis/goid
    - os: osx
      before_install:
        - go get NiuStar/utils
        - go get NiuStar/log
        - go get github.com/petermattis/goid
    - os: windows
      before_install:
        - go get NiuStar/utils
        - go get NiuStar/log
        - go get github.com/petermattis/goid

script:
  - cd examples && go build && ls -l && cd ..